name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at every 6th hour" (see https://crontab.guru/every-6-hours)
    - cron: "0 */6 * * *"

env:
  ALGOLIA_APP_ID: ${{secrets.ALGOLIA_APP_ID}}
  ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
  ALGOLIA_INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
  DRUPAL_BASEURL: ${{secrets.DRUPAL_BASEURL}}
  GOOGLE_ANALYTICS_ID: ${{secrets.GOOGLE_ANALYTICS_ID}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist
